services:
  frontend:
    image: angular
    build: ./frontend
    container_name: angular
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - frontend_network

  backend:
    image: nodejs
    build: ./backend
    container_name: nodejs
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend_network

  database:
    image: mysql:8.4.0-oraclelinux9
    container_name: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 3

networks:
  backend_network:
    name: backend_network
  frontend_network:
    name: frontend_network
